version: "3.8"
services:

    app:
        build:
            args:
                user: Agora
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: agora
        container_name: agora-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - agora-net

    db:
        image: mysql:latest
        container_name: agora-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: agora-mysql
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - agora-net

    webserver:
        image: nginx:alpine
        container_name: agora-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - agora-net

networks:
    agora-net:
        driver: bridge
